name: New Workflow
on:
  push:
    branches-ignore:
      - main
      - dev
      
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      id: set-result
      with:
        script: return "Hello!"
        result-encoding: string
    - name: Get result
      run: echo "${{steps.set-result.outputs.result}}"
    - name: Print Context
      run: echo "${{context}}"
